#include "scripts\const.inc"

global Scene;
global Keyboard;
global actor;


// Declare global state variables

global WinSubtitles;
global SubWindow;
global WinCaption;
global WinMenu;

global PortraitType = PORT_NORMAL;
global EndingPoints;
global EndingType;
global AxeType;

global SubtitleSetting;
global TTFFont;
global LangFile;

global VoiceActing;
global GermanVoice = false;

// Declare global music variables
global MusicCurrentAmbient;
global MusicPlayingAmbient;

// Black chamber globals
global BlackChamberPanelState;
global BlackChamberWiresFixed;
global BlackChamberWindowsOpen;
global BlackChamberDoorOpen;

// Computer room globals
global ComputerRoomKeyPos;
global ComputerRoomColourPart;
global ComputerRoomMistake;
global ComputerRoomBodySucked;
global ComputerRoomCut;
global ComputerRoomBloodyBodyAxed;

// Nav room globals
global StationPowered;
global StationRotation;
global CradleSafety;
global CradleLowered;

// Living room globals
global LivingRoomTableUp;
global LivingRoomArmTaken;
global LivingRoomDiscTaken;
global LivingRoomBoxTaken;
global LivingRoomDrSaltTaken;
global LivingRoomExtTaken;
global LivingRoomDisc1Seen;
global LivingRoomDisc2Seen;
global LivingRoomDisc3Seen;
global LivingRoomBloodyNav;
global LivingRoomFridgeDone;
global LivingRoomMirror;
global LivingRoomArmSeen;
global LivingRoomSmellCount;
global LivingRoomChainHacked;

// Corridor global
global CorridorDirection;
global CorridorSegment;

// Beach globals
global BeachSeen;
global ExtDoorCount;

// Medbay
global FireOut;
global MedBayEnvTaken;
global CorridorSequenceDone;
global MedBayLaserBatt;
global MedBayBodyComplete;
global MedBayBoxOnDesk;
global MedBayEyesTaken;
global MedBayQuarDone;

// Sleeping Quarters Globals
global ShowerHeadDone;

// Lab globals
global LabAxeTaken;
global TortureDone;
global LabBomb;
global LabBlown;

// Store globals
global CoatSearched;
global MESCounter;

global FreezerBlanketMan;

global SampleInserted;
global CardProgrammed;
global deadManWalking;
global gameFinished;

global SeenFanDeath;
global SeenNavDeath;
global SeenSleepDeath;
global SeenCompDeath;

global Strapped;

global AltMenu;
global AltMenuOn;
