// ***** global constants

// directions
global DI_UP       =0;
global DI_UPRIGHT  =1;
global DI_RIGHT    =2;
global DI_DOWNRIGHT=3;
global DI_DOWN     =4;
global DI_DOWNLEFT =5;
global DI_LEFT     =6;
global DI_UPLEFT   =7;


// text alignment
global TAL_LEFT  =0;
global TAL_RIGHT =1;
global TAL_CENTER=2;


// vertical text alignment
global VAL_TOP=0;
global VAL_CENTER=1;
global VAL_BOTTOM=2;

// portratis types
global PORT_NORMAL=0;
global PORT_PUZZLED=1;
global PORT_PISSED=2;
global PORT_POCKING=3;
global PORT_NONE=4;
global PORT_ARTHUR=5;
global PORT_REDDISC=6;
global PORT_GREENDISC=7;
global PORT_BLUEDISC=8;
global PORT_MES=9;
global PORT_CREW1=10;
global PORT_CREW2=11;
global PORT_CREW3=12;
global PORT_CREW4=13;


// ambients
global AMBIENT_SILENCE=0;
global AMBIENT_SCARY=1;
global AMBIENT_NORMAL=2;

// Axe types
global AXE_CHAIN=1;
global AXE_TUBE=2;
global AXE_PIPE=3;
global AXE_LEG=4;

// Ending types
global END_NONE=0;
global END_GOOD=1;
global END_BAD=2;
global END_QUAR=3;
global END_FRIDGE=4;
global END_COMEDY=5;
global END_TORTURE=6;
global END_SPACE=7;
global END_ELEC=8;
