#include "scripts\base.inc"
#include "scripts\music.inc"

PlayAmbient(AMBIENT_SILENCE, "WHITE");

// here comes the stuff which initializes the scene

actor.SkipTo(633, 347);
actor.Direction = DI_DOWN;
actor.Active = true;


////////////////////////////////////////////////////////////////////////////////
// scene state
global StateWhiteChamber;


// default values
if(StateWhiteChamber==null)
{
  StateWhiteChamber.Visited = false;
  // add scene states here
}



////////////////////////////////////////////////////////////////////////////////
// setup scene according to state variables



////////////////////////////////////////////////////////////////////////////////
if(!StateWhiteChamber.Visited)
{
  StateWhiteChamber.Visited = true;

  // this is our first visit in this scene...
}

