#include "scripts\base.inc"
#include "scripts\music.inc"

// here comes the stuff which initializes the scene

actor.SkipTo(692, 608);
actor.Direction = DI_LEFT;
actor.Active = true;

PlayAmbient(AMBIENT_SILENCE, "BEACH");


////////////////////////////////////////////////////////////////////////////////
// scene state
global StateBeach;


// default values
if(StateBeach==null)
{
  StateBeach.Visited = false;
  // add scene states here
}



////////////////////////////////////////////////////////////////////////////////
// setup scene according to state variables


////////////////////////////////////////////////////////////////////////////////
if(!StateBeach.Visited)
{
  StateBeach.Visited = true;

  // this is our first visit in this scene...
}

BeachSeen = true;
