#include "scripts\base.inc"


////////////////////////////////////////////////////////////////////////////////
on "leftclick"
{
 	actor.GoToObject(this);
}

on "lookat"
{
 	actor.GoToObject(this);
	PortraitType = PORT_POCKING;
	actor.Talk("/LIVING0027/It's like a gaping mouth, who knows where it leads");
}

on "take"
{
 	actor.GoToObject(this);
	PortraitType = PORT_POCKING;
	actor.Talk("/LIVING0028/I'm not going anywhere near that");
}
