#include "scripts\base.inc"
#include "scripts\music.inc"

// here comes the stuff which initializes the scene

actor.SkipTo(247, 333);
actor.Direction = DI_DOWN;
actor.Active = true;

PlayAmbient(AMBIENT_NORMAL, "NONE");


////////////////////////////////////////////////////////////////////////////////
// scene state
global StateMedBayNormal;


// default values
if(StateMedBayNormal==null)
{
  StateMedBayNormal.Visited = false;
  // add scene states here
}



////////////////////////////////////////////////////////////////////////////////
// setup scene according to state variables



////////////////////////////////////////////////////////////////////////////////
if(!StateMedBayNormal.Visited)
{
  StateMedBayNormal.Visited = true;

  // this is our first visit in this scene...
}

